version: '3.8'

services:
  db:
    image: postgres:15
    container_name: starburger_db
    volumes:
      - ~/.pg/pg_data/astrouser:/var/lib/postgresql/data
    env_file:
      - .env_db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
