# Generated by Django 4.2.3 on 2023-08-21 16:49

from django.db import migrations


def set_price_for_order_item(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items_iter = OrderItem.objects.all().iterator()
    for order_item in order_items_iter:
        order_item.price = order_item.product.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(set_price_for_order_item)
    ]
