# Generated by Django 4.2.3 on 2023-08-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230821_1649'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_phonenu_5f4ceb_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATE', 'Создан'), ('PREPARE', 'Готовится'), ('DELIVER', 'Доставляется'), ('DONE', 'Выполнен')], default='CREATE', max_length=15, verbose_name='Статус заказа'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber', 'status'], name='foodcartapp_phonenu_4af990_idx'),
        ),
    ]
