# Generated by Django 4.2.3 on 2023-08-21 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_comment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_phonenu_4af990_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateField(blank=True, null=True, verbose_name='Звонок'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateField(blank=True, null=True, verbose_name='Доставлен'),
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber', 'status', 'registered_at', 'called_at', 'delivered_at'], name='foodcartapp_phonenu_d60526_idx'),
        ),
    ]
