# Generated by Django 4.2.3 on 2023-08-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_called_at_alter_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Картой')], default='', max_length=10, verbose_name='Форма оплаты'),
        ),
    ]
