# Generated by Django 4.2.3 on 2023-08-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_payment_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_phonenu_d60526_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта')], default='', max_length=10, verbose_name='Форма оплаты'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber', 'status', 'registered_at', 'called_at', 'delivered_at', 'payment_type'], name='foodcartapp_phonenu_20923b_idx'),
        ),
    ]
