# Generated by Django 4.2.3 on 2023-08-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_restaurant_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='near_restaurant',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ресторан рядом'),
        ),
    ]
