# Generated by Django 4.2.3 on 2023-09-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
