# Generated by Django 4.2.3 on 2023-09-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='near_restaurant',
        ),
    ]
